from tkinter import *
window = Tk()
window.title("login app")
window.geometry("400x400")
frame = Frame(master=window,height=200,width=360,bg="#d0efff")
Label1 = Label(frame,text="Full Name",bg="#3895d3",fg="white",width=12)
Label2 = Label(frame,text="Email Id",bg="#0099ff",fg="white",width=12)
Label3 = Label(frame,text="Enter Password",bg="#0099ff",fg="white",width=12)
nameentry = Entry(frame)
emailentry = Entry(frame)
passentry = Entry(frame,show="*")
def display():
    name = nameentry.get()
    great = "hey "+name
    message = "\n congratulations on your new account!!!!!!"
    textbox.insert(END,great)
    textbox.insert(END,message)
textbox = Text(bg = "#00AEFF",fg = "black")
button = Button(text = "Create Account",command=display,bg = "red")
frame.place(x=20,y=0)
Label1.place(x=20,y=20)
nameentry.place(x=150,y=20)
Label2.place(x=20,y=80)
emailentry.place(x=150,y=80)
Label3.place(x=20,y=140)
passentry.place(x=150,y=140)
button.place(x=130,y=210)
textbox.place(y=250)
window.mainloop()